#! /bin/sh

# Kill existing processes
pkill polybar
pkill picom
if [[ $(xrandr -q | grep 'LVDS1 connected') ]]; then
  xrandr --output LVDS1 --primary --mode 1280x800 --rotate normal --output VGA1 --mode 1400x1050 --rotate normal --right-of LVDS1
fi

bspc monitor LVDS1 -d 1 2 3 4
bspc monitor VGA1 -d 5 6 7

# Set wallpaper
#feh --randomize --bg-fill ~/Pictures/backgrounds/* &

# Launch polybar
#polybar top &

# pgrep -x sxhkd > /dev/null || sxhkd &
# Set mouse cursor theme
xsetroot -cursor_name left_ptr

bspc config focus_follows_pointer true
bspc config pointer_follows_focus false
bspc config pointer_follows_monitor true
bspc config pointer_motion_interval 7
bspc config pointer_modifier mod4

bspc config border_width 2
bspc config window_gap 8

bspc config split_ratio 0.52
bspc config borderless_monocle true
bspc config gapless_monocle false

bspc config removal_adjustment true
bspc config top_padding 5

# rules
#bspc rule -a feh state=floating
#bspc rule -a Gimp desktop='^8' state=floating follow=on
#bspc rule -a Chromium desktop='^2'
#bspc rule -a mplayer2 state=floating
#bspc rule -a Kupfer.py focus=on
#bspc rule -a Screenkey manage=off

# start resource
xrdb merge ~/.Xresources

~/.config/bspwm/scripts/launch.sh &
~/.config/polybar/launch.sh

# launch notification daemon
dunst -config $HOME/.config/bspwm/dunstrc &

# start compositor
picom --config $HOME/.config/bspwm/picom_configurations/1.conf &

# Start keybindings
sxhkd &

flameshot &

wmname LG3D
